version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Admin123!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
    container_name: backend
    depends_on:
      - sqlserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=EmployeeDb;User Id=sa;Password=Admin123!;Encrypt=True;TrustServerCertificate=True
    ports:
      - "5000:5000"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/html:/usr/share/nginx/html:ro

  frontend-builder:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend-builder
    command: sh -c "cp -r /app/dist/* /output"
    volumes:
      - ./nginx/html:/output
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
