global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "employee-api"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]

rule_files:
  - "alert.rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ["alertmanager:9093"]
